name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Megalinter
        uses: oxsecurity/megalinter@839e6d63c0423eb74ce2578225f8b8b4bed63ede # v8.4.1
        env:
          APPLY_FIXES: "none"
          BASH_SHFMT_DISABLE_ERRORS: "false"
          DISABLE_LINTERS: MARKDOWN_MARKDOWN_LINK_CHECK,REPOSITORY_CHECKOV,REPOSITORY_DEVSKIM,REPOSITORY_SECRETLINT,REPOSITORY_TRIVY,REPOSITORY_TRUFFLEHOG,SPELL_CSPELL
          FILTER_REGEX_EXCLUDE: .*/ISSUE_TEMPLATE/.*
          FLAVOR_SUGGESTIONS: "false"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JSON_PRETTIER_DISABLE_ERRORS: "false"
          LOG_LEVEL: WARN
          MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: "false"
          PRINT_ALL_FILES: "false"
          PRINT_ALPACA: "false"
          SHOW_ELAPSED_TIME: "true"
          SPELL_MISSPELL_DISABLE_ERRORS: "true"
          VALIDATE_ALL_CODEBASE: "true"
          YAML_PRETTIER_DISABLE_ERRORS: "false"
